apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" # for dynamic volume provisioning
  # volumeName: "ebs-static" # for static volume provisioning
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1 
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic
spec:
  containers:
  - name: nginx
    image:  nginx
    volumeMounts:
    - name: ebs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic
    persistentVolumeClaim:
      claimName:  ebs-dynamic

---
apiVersion: v1 
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
  - name: ebs-dynamic
    protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30007