apiVersion: v1 
kind: PersistentVolume
metadata:
  name: expense-efs
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: "" # dynamic storage class name
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d980b179fa64a43b
  capacity:
    storage: 5Gi

---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: expense-efs
spec:
  volumeName: expense-efs
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 
apiVersion: v1 
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-static
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-static
    persistentVolumeClaim:
      claimName:  expense-efs

---
apiVersion: v1  
kind: Service
metadata:
  name: efs-static
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: efs-static
    protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30007