apiVersion: v1 
kind: Pod
metadata:
  name: labels 
  labels: # labels are key-value tags added to resources to identify and group them
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  - name: nginx 
    image: nginx
