apiVersion: v1 
kind: Pod 
metadata:
  name: pod-secret
  labels:
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "120m"
        memory: "128Mi"
    envFrom:
    - configMapRef:
        name: nginx-config
    - secretRef:
        name: pod-secret