apiVersion: v1 
kind: Service
metadata: 
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    module: backend
  ports: 
  - name: nginx-svc-port
    protocol: "tcp"
    port: 80 #servicePort
    targetPort: 80 #containerPort